# Generated by Django 5.2.8 on 2025-12-05 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('report_type', models.CharField(choices=[('FRAUD', 'Fraude'), ('HARASSMENT', 'Acoso'), ('INAPPROPRIATE_LANGUAGE', 'Lenguaje inapropiado'), ('MISLEADING_CONTENT', 'Contenido engañoso'), ('OTHER', 'Otro')], default='OTHER', help_text='Tipo de conducta reportada', max_length=30)),
                ('reason', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('UNDER_REVIEW', 'En Revisión'), ('ACCEPTED', 'Aceptado'), ('REJECTED', 'Rechazado')], default='UNDER_REVIEW', max_length=12)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'report',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ListingReport',
            fields=[
                ('report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='listingreport', serialize=False, to='inquiries.report')),
            ],
            options={
                'db_table': 'listing_report',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UserReport',
            fields=[
                ('report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='userreport', serialize=False, to='inquiries.report')),
            ],
            options={
                'db_table': 'user_report',
                'managed': True,
            },
        ),
    ]
