# Generated by Django 5.2.8 on 2025-12-05 13:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('listings', '0003_comment'),
        ('operations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('report_type', models.CharField(choices=[('FRAUD', 'Fraude'), ('HARASSMENT', 'Acoso'), ('INAPPROPRIATE_LANGUAGE', 'Lenguaje inapropiado'), ('MISLEADING_CONTENT', 'Contenido engañoso'), ('OTHER', 'Otro')], default='OTHER', help_text='Tipo de conducta reportada', max_length=30)),
                ('reason', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('UNDER_REVIEW', 'En Revisión'), ('ACCEPTED', 'Aceptado'), ('REJECTED', 'Rechazado')], default='UNDER_REVIEW', max_length=12)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_made', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, db_column='reviewed_by', help_text='Administrador que revisó el reporte', null=True, on_delete=django.db.models.deletion.SET_NULL, to='operations.admin')),
            ],
            options={
                'db_table': 'report',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ListingReport',
            fields=[
                ('report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='listingreport', serialize=False, to='inquiries.report')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='listings.listing')),
            ],
            options={
                'db_table': 'listing_report',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UserReport',
            fields=[
                ('report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='userreport', serialize=False, to='inquiries.report')),
                ('reported_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_report',
                'managed': True,
            },
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['reporter'], name='ix_report_reporter'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['status'], name='ix_report_status'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['reviewed_by'], name='ix_report_reviewer'),
        ),
        migrations.AddIndex(
            model_name='listingreport',
            index=models.Index(fields=['listing'], name='ix_lreport_listing'),
        ),
        migrations.AddIndex(
            model_name='userreport',
            index=models.Index(fields=['reported_user'], name='ix_ureport_user'),
        ),
    ]
