# Generated by Django 5.2.8 on 2025-12-05 18:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inquiries', '0001_initial'),
        ('listings', '0002_initial'),
        ('operations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='reporter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_made', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='report',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, db_column='reviewed_by', help_text='Administrador que revisó el reporte', null=True, on_delete=django.db.models.deletion.SET_NULL, to='operations.admin'),
        ),
        migrations.AddField(
            model_name='listingreport',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='listings.listing'),
        ),
        migrations.AddField(
            model_name='userreport',
            name='reported_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['reporter'], name='ix_report_reporter'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['status'], name='ix_report_status'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['reviewed_by'], name='ix_report_reviewer'),
        ),
        migrations.AddIndex(
            model_name='listingreport',
            index=models.Index(fields=['listing'], name='ix_lreport_listing'),
        ),
        migrations.AddIndex(
            model_name='userreport',
            index=models.Index(fields=['reported_user'], name='ix_ureport_user'),
        ),
    ]
