# Generated by Django 5.2.8 on 2025-12-05 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inquiries', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listingreport',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='report',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='userreport',
            options={'managed': False},
        ),
    ]
