# Generated by Django 5.2.8 on 2025-11-22 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='suspensionEndDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
