# Generated by Django 5.2.8 on 2025-12-08 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_landlord_options_alter_student_options_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='landlord',
            table='users_landlord',
        ),
        migrations.AlterModelTable(
            name='student',
            table='users_student',
        ),
        migrations.AlterModelTable(
            name='user',
            table='users_user',
        ),
    ]
