# Generated by Django 5.2.8 on 2025-11-23 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_listing_landlord_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landlord',
            name='listings',
            field=models.ManyToManyField(blank=True, to='users.listing'),
        ),
        migrations.AlterField(
            model_name='student',
            name='favoriteListings',
            field=models.ManyToManyField(blank=True, to='users.listing'),
        ),
    ]
