# Generated by Django 5.2.8 on 2025-11-28 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(error_messages={'unique': 'Ya existe una cuenta registrada con ese correo.'}, max_length=254, unique=True, verbose_name='Dirección de correo'),
        ),
    ]
