# Generated by Django 5.2.8 on 2025-12-05 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'managed': False, 'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='listing',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='listingphoto',
            options={'managed': False, 'ordering': ['sort_order', 'id']},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'managed': False, 'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='zone',
            options={'managed': False},
        ),
    ]
