# Generated by Django 5.2.8 on 2025-12-08 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_alter_comment_options_alter_listing_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'favorite',
                'ordering': ['-created_at'],
                'managed': False,
            },
        ),
        migrations.AlterModelTable(
            name='comment',
            table='comment',
        ),
        migrations.AlterModelTable(
            name='listing',
            table='listing',
        ),
        migrations.AlterModelTable(
            name='listingphoto',
            table='listing_photo',
        ),
        migrations.AlterModelTable(
            name='review',
            table='review',
        ),
        migrations.AlterModelTable(
            name='zone',
            table='zone',
        ),
    ]
