# Generated by Django 5.2.8 on 2025-12-03 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listingphoto',
            name='mime_type',
        ),
        migrations.RemoveField(
            model_name='listingphoto',
            name='size_bytes',
        ),
        migrations.RemoveField(
            model_name='listingphoto',
            name='url',
        ),
        migrations.AddField(
            model_name='listingphoto',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='listing_photos/'),
        ),
    ]
