# Generated by Django 5.2.8 on 2025-12-03 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_remove_listingphoto_mime_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listingphoto',
            name='image',
            field=models.ImageField(default='', upload_to='listing_photos/'),
            preserve_default=False,
        ),
    ]
